// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjifpblazlsecdgskuwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqaWZwYmxhemxzZWNkZ3NrdXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjM1NzMsImV4cCI6MjA2MDg5OTU3M30.WGGuTl62DoX1UErPy__CZ7Ok4aa-jV0AFBD8zzRyrlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);